apiVersion: v1
kind: Pod
metadata:
  name: pod-red.yml
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: red
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: red